---

- hosts: all
  gather_facts: false
  remote_user: root
  tasks: 

    - name: Update
      raw: apt-get -y --allow-unauthenticated update || true

    - name: Ensure python is available
      raw: test -e /usr/bin/python || apt install -y --allow-unauthenticated python-minimal

    - name: Ensure python-apt is available
      raw: test -d /usr/share/python-apt || apt install -y --allow-unauthenticated python-apt

    - name: Upgrade
      raw: apt-get -y --allow-unauthenticated upgrade

- hosts: nc
  remote_user: root
  tasks: 

    - name: Install php
      apt:
        name: php7.0
        state: present
        allow_unauthenticated: yes

    - name: Install php7.0-cgi
      apt:
        name: php7.0-cgi
        state: present
        allow_unauthenticated: yes

    - name: Install php7.0-mysql
      apt:
        name: php7.0-mysql
        state: present
        allow_unauthenticated: yes

    - name: Install apache2
      apt:
        name: apache2
        state: present
        allow_unauthenticated: yes

    - name: Install mariadb-server
      apt:
        name: mariadb-server
        state: present
        allow_unauthenticated: yes

    - name: Install python-mysqldb
      apt:
        name: python-mysqldb
        state: present
        allow_unauthenticated: yes
